package cn.enn.portal.jobCenter.core;

public enum ScheduleActionType {
    USER_SCHEDULE,
    SYSTEM_STARTUP_SCHEDULE,
    USER_SHUTDOWN,
    SYSTEM_SHUTDOWN,
    SYSTEM_SCHEDULE,
    OVERRIDE_SHUTDOWN,
    RESOLVER_CREATE,
    RESOLVER_UPDATE,
    RESOLVER_DELETE,
    RESOLVER_SHUTDOWN,
    MANUAL_START,
    MANUAL_STOP
}
